### ISSUE TITLE
Image Upload Not working issue with sql.

### ISSUE THREAD

**Issue by ShamimShahriyar** [PHPVibe/PHPVibe-Video-Sharing-CMS#21]
line 48; PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect integer value: '' for column `database1`.`vibe_images`.`nsfw` at row 1 in /var/www/html/PHPVibe/app/classes/ez_sql_mysqli.php:264\nStack trace:\n#0 /var/www/html/PHPVibe/app/classes/ez_sql_mysqli.php(264): mysqli->query()\n#1 /var/www/html/PHPVibe/views/addimage.route.php(35): ezSQL_mysqli->query()\n#2 /var/www/html/PHPVibe/index.php(176): include_once('...')\n#3 {main}\n  thrown in /var/www/html/PHPVibe/app/classes/ez_sql_mysqli.php on line 264', referer: https://shamimshahriyar.xyz/add-image
Pleas mentinon how much memory(PHP) limit is necessary to upload a image. Thanks:)

**Comment by ShamimShahriyar** [comment]
Hare is detail log of nginx server also.
2024/08/14 22:38:39 [error] 450222#450222: *55 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Implicit conversion from float 213.36384439359267 to int loses precision in /var/www/html/PHPVibe/app/classes/class.images.php on line 417; PHP message: PHP Deprecated:  Implicit conversion from float 213.36384439359267 to int loses precision in /var/www/html/PHPVibe/app/classes/class.images.php on line 485; PHP message: PHP Deprecated:  Implicit conversion from float 213.36384439359267 to int loses precision in /var/www/html/PHPVibe/app/classes/class.images.php on line 419; PHP message: PHP Deprecated:  Implicit conversion from float 213.36384439359267 to int loses precision in /var/www/html/PHPVibe/app/classes/class.images.php on line 485; PHP message: PHP Deprecated:  Implicit conversion from float 26.681922196796336 to int loses precision in /var/www/html/PHPVibe/app/classes/class.images.php on line 511" while reading response header from upstream, client: 162.158.190.67, server: shamimshahriyar.xyz, request: "POST /dashboard/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.3-fpm.sock:", host: "shamimshahriyar.xyz", referrer: "https://shamimshahriyar.xyz/dashboard/"
2024/08/14 23:00:51 [error] 496252#496252: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect integer value: '' for column `database_A`.`vibe_images`.`nsfw` at row 1 in /var/www/html/PHPVibe/app/classes/ez_sql_mysqli.php:264
Stack trace:
#0 /var/www/html/PHPVibe/app/classes/ez_sql_mysqli.php(264): mysqli->query()
#1 /var/www/html/PHPVibe/views/addimage.route.php(35): ezSQL_mysqli->query()
#2 /var/www/html/PHPVibe/index.php(176): include_once('...')
#3 {main}
  thrown in /var/www/html/PHPVibe/app/classes/ez_sql_mysqli.php on line 264" while reading response header from upstream, client: 172.71.124.119, server: shamimshahriyar.xyz, request: "POST /add-image HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.3-fpm.sock:", host: "shamimshahriyar.xyz", referrer: "https://shamimshahriyar.xyz/add-image"

**Comment by ShamimShahriyar** [comment]
Solved! nsfw column in the vibe_images table is INT and does not accept NULL values set it to varchar and your image should get uploaded.
I'm using Nginx so don't know what it done while making the database manually set it to varchar and now it's working. Should anyone be working modify SQL before proceeding.
Attached an image for solution.
And you should set resource limitation in php.ini
 
![image](https://github.com/user-attachments/assets/04c2ecb7-74f2-4fc2-b7b4-be5761085b45)
