### ISSUE TITLE
while importing from Playlist 2nd page shows white blank page no videos

### ISSUE THREAD

**Issue by geekguide** [PHPVibe/PHPVibe-Video-Sharing-CMS#3]
Hello while importing from Playlist white page shows on 2nd page,only page 1 working for importing videos not after that...

**Comment by PHPVibe** [comment]
Hi! What's the error in the server's error log?

**Comment by geekguide** [comment]
Hello i didn't check the server error log at that time but when click on second page it just shows white page. no videos ...please check your demo.Also please check the forum there are other user seeking your help from long time.

**Comment by PHPVibe** [comment]
I've already answered on the forums.

**Comment by geekguide** [comment]
Hello in the Recent Updates by you have u solve this import Playlist issue ? Thank you

**Comment by geekguide** [comment]
> Hi! What's the error in the server's error log?

"500 Internal Server Error" while import from playlist from YouTube importer on page 2.....

while checking server error i got following

2023/05/22 14:03:19 [error] 18730#0: *1 FastCGI sent in stderr: ＂PHP message: PHP Fatal error:  Uncaught Exception: Error 400 The request specifies an invalid page token. : invalidPageToken in /www/wwwroot/website.com/app/classes/class.youtube.php:547
Stack trace:
#0 /www/wwwroot/website.com/app/classes/class.youtube.php(357): Youtube-＞decodeList()
#1 /www/wwwroot/website.com/moderator/yt_playlistsearch.php(26): Youtube-＞getPlaylistItemsByPlaylistId()
#2 /www/wwwroot/website.com/moderator/index.php(42): require_once(＇...＇)
#3 {main}
  thrown in /www/wwwroot/website.com/app/classes/class.youtube.php on line 547＂ while reading response header from upstream, client: 172.71.186.114, server: website.com, request: ＂GET /moderator/?sk=yt_playlistsearch&amp;pID=PLrWQ81hxsOTJllTp9Yt56oyEcGzp3ZEDa&amp;imode=2&amp;bpp=15&amp;categ[0]=1&amp;order=relevance&amp;owner=1&amp;auto=0&amp;name=shabad%20%3Cem%3Eby%20Rajveer%20Singh%3C/em%3E&amp;p=2 HTTP/1.1＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-81.sock:＂, host: ＂website.com＂, referrer: ＂https://website.com/moderator/?sk=yt_playlistsearch&amp;pID=PLrWQ81hxsOTJllTp9Yt56oyEcGzp3ZEDa&amp;imode=2&amp;bpp=15&amp;categ[0]=1&amp;order=relevance&amp;owner=1&amp;p=1＂
2023/05/22 14:03:24 [error] 18730#0: *1 FastCGI sent in stderr: ＂PHP message: PHP Deprecated:  Implicit conversion from float 9.4 to int loses precision in /www/wwwroot/website.com/app/functions/functions.global.php on line 507PHP message: PHP Deprecated:  Implicit conversion from float 7.55 to int loses precision in /www/wwwroot/website.com/app/functions/functions.global.php on line 507PHP message: PHP Deprecated:  Implicit conversion from float 9.366666666666667 


Please check and solve this .Thank you

**Comment by PHPVibe** [comment]
It sounds like the API doesn't return a second page for that search, even if PHPVibe tries to force it. 
Cheers!

**Comment by PHPVibe** [comment]
I've deprecated the importer, for now I'll need to check what changes has Youtube made, it seems it has changed the page tokens and that's why it keeps failing to move to page 2.
